namespace: myapp
backend:
  replicaCount: 1
  containerPort: 3000

frontend:
  replicaCount: 2
  containerPort: 8080

database:
  replicaCount: 1
  dbUser: user
  dbPassword: password
  dbName: mydatabase
  dbHost: postgres-service
  dbPort: 5432

image:
  name: us-central1-docker.pkg.dev/brave-inn-477912-q1/fredi-is-useless/app
  tag: latest

pvcCapacity: 10Gi
pvCapacity: 10Gi
