apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: {{ .Values.image.name }}:{{ .Values.image.tag}}    # <- must match the image tag you built
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.backend.containerPort }}   # change to your app's port
          
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.dbUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.dbPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.database.dbName }}
            - name: POSTGRES_HOST
              value: {{ .Values.database.dbHost }}
            - name: POSTGRES_PORT
              value: {{ .Values.database.dbPort | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: {{ .Values.backend.containerPort }} # port inside the cluster
      targetPort: 3000  # container port