apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace:  {{ .Values.namespace }}
data:
  nginx.conf: |
{{ .Files.Get "nginx-conf/nginx.conf" | indent 4 }}
  index.html: |
{{ .Files.Get "nginx-conf/index.html" | indent 4 }}
